config/routes.rb
FPCollaboration::Application.routes.draw do
  root :to => "scrapbooks#new"
  
  resources :scrapbooks do
    resources :pages
  end

  devise_for :admins

  devise_for :collaborators

  devise_for :users

  

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :name
end

app/models/collaborator.rb
class Collaborator < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :description, :logo_image, :name
end

app/models/page.rb
class Page < ActiveRecord::Base
  attr_accessible :scrapbook_id, :html
  belongs_to :parent
end

app/models/scrapbook.rb
class Scrapbook < ActiveRecord::Base
  attr_accessible :name
  has_many :pages
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :avatar_image, :email, :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

before_filter :load_scrapbook
before_filter :authenticate_user!
  # GET /pages
  # GET /pages.json
  def index
    @pages = @scrapbook.pages.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pages }
    end
  end

  # GET /pages/1
  # GET /pages/1.json
  def show
    @page = @scrapbook.pages.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @page }
    end
  end

  # GET /pages/new
  # GET /pages/new.json
  def new
    @page = @scrapbook.pages.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @page }
    end
  end

  # GET /pages/1/edit
  def edit
    @page = @scrapbook.pages.find(params[:id])
  end

  # POST /pages
  # POST /pages.json
  def create
    @page = @scrapbook.pages.new(params[:page])
    @page.html = params[:page][:html]
    puts("CREATE   CREATE   "+@page.html)
    respond_to do |format|
      if @page.save
        format.html { redirect_to [@scrapbook, @page], notice: 'Page was successfully created.' }
        format.json { render json: @page, status: :created, location: @page }
      else
        format.html { render action: "new" }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pages/1
  # PUT /pages/1.json
  def update
    @page = @scrapbook.pages.find(params[:id])
    @page.html = params[:html]
    respond_to do |format|
      if @page.update_attributes(params[:page])
        format.html { redirect_to [@scrapbook, @page], notice: 'Page was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1
  # DELETE /pages/1.json
  def destroy
    @page = @scrapbook.pages.find(params[:id])
    @page.destroy

    respond_to do |format|
      format.html { redirect_to scrapbook_pages_path(@scrapbook) }
      format.json { head :no_content }
    end
  end

  private

    def load_scrapbook
      @scrapbook = Scrapbook.find(params[:scrapbook_id])
    end

end

app/controllers/scrapbooks_controller.rb
class ScrapbooksController < ApplicationController
  before_filter :authenticate_user!
  # GET /scrapbooks
  # GET /scrapbooks.json
  def index
    @scrapbooks = Scrapbook.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @scrapbooks }
    end
  end

  # GET /scrapbooks/1
  # GET /scrapbooks/1.json
  def show
    @scrapbook = Scrapbook.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @scrapbook }
    end
  end

  # GET /scrapbooks/new
  # GET /scrapbooks/new.json
  def new
    @scrapbook = Scrapbook.new
    @page = @scrapbook.pages.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @scrapbook }
    end
  end

  # GET /scrapbooks/1/edit
  def edit
    @scrapbook = Scrapbook.find(params[:id])
  end

  # POST /scrapbooks
  # POST /scrapbooks.json
  def create
    @scrapbook = Scrapbook.new(params[:scrapbook])
    @page = @scrapbook.pages.new

    respond_to do |format|
      if @scrapbook.save
        format.html { redirect_to new_scrapbook_page_url(@scrapbook), notice: 'Scrapbook was successfully created.' }
        format.json { render json: @scrapbook, status: :created, location: @scrapbook }
      else
        format.html { render action: "new" }
        format.json { render json: @scrapbook.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /scrapbooks/1
  # PUT /scrapbooks/1.json
  def update
    @scrapbook = Scrapbook.find(params[:id])

    respond_to do |format|
      if @scrapbook.update_attributes(params[:scrapbook])
        format.html { redirect_to @scrapbook, notice: 'Scrapbook was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @scrapbook.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scrapbooks/1
  # DELETE /scrapbooks/1.json
  def destroy
    @scrapbook = Scrapbook.find(params[:id])
    @scrapbook.destroy

    respond_to do |format|
      format.html { redirect_to scrapbooks_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/scrapbooks_helper.rb
module ScrapbooksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "FPCollaboration" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">FPCollaboration</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><%= link_to "Hangout", "/path1"  %></li>
              <li><%= link_to "Explore", "/path2"  %></li>
              <li><%= link_to "Play", "/path3"  %></li>
              <li><%= link_to "Logout", destroy_user_session_path, :method => :delete  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header"></li>
              <li><%= link_to "Fashion", "/path1"  %></li>
              <li><%= link_to "Sports", "/path2"  %></li>
              <li><%= link_to "Beauty", "/path3"  %></li>
              <li><%= link_to "Science", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2013</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/pages/_form.html.erb
  

  <div id="scrapbook-side-bar">
      <h3>Scraps</h3>
  <div>
    <ul>
      <li class="scrap-options">
        <div class="scrap small-scrap">
          <%= image_tag "redheart.png" %>
        </div>
      </li>
      <li class="scrap-options">
        <div class="scrap small-scrap">
          <%= image_tag "pink-backpack.png" %>
        </div>
      </li>
      <li class="scrap-options">
        <div class="scrap small-scrap">
          <%= image_tag "bow.png" %>
        </div>
      </li>
      <li class="scrap-options">
        <div class="scrap small-scrap">
          <%= image_tag "stamp.png" %>
        </div>
      </li>
      <li class="scrap-options">
        <div class="scrap small-scrap">
          <%= image_tag "rainbows.png" %>
        </div>
      </li>
    </ul>
  </div>
  <h3>Backgrounds</h3>
  <div>
    <div class="background-button">
      <%= image_tag "Paper_texture_v5_by_bashcorpo.jpg" %>
    </div>
    <div class="background-button">
      <%= image_tag "tropical-background.jpg" %>
    </div>
    <div class="background-button">
      <%= image_tag "Background_stamps.jpg" %>
    </div>
    <div class="background-button">
      <%= image_tag "Paper_texture_1_by_wojtar_stock.jpg" %>
    </div>
  </div>
  <h3>Borders</h3>
  <div>
    <ul>
      <li>List item one</li>
      <li>List item two</li>
      <li>List item three</li>
    </ul>
  </div>

  </div>

  <div class="page">

  </div>
<%= form_for([@scrapbook, @page], :html => { :class => 'form-horizontal' }) do |f| %>
  <div class="control-group">
    <%= f.label :scrapbook_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.hidden_field :html, :class => 'text_field', :id => 'new_scrapbook_page_html' %>

    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' ,:id=> 'new_scrapbook_page' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                scrapbook_pages_path(@scrapbook), :class => 'btn' %>
  </div>

<% end %>

app/views/pages/edit.html.erb
<%- model_class = Page -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/pages/index.html.erb
<%- model_class = Page -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:scrapbook_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @pages.each do |page| %>
      <tr>
        <td><%= link_to page.id, scrapbook_page_path(@scrapbook, page) %></td>
        <td><%= page.scrapbook_id %></td>
        <td><%=l page.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_scrapbook_page_path(@scrapbook, page), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      [@scrapbook, page],
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_scrapbook_page_path(@scrapbook),
            :class => 'btn btn-primary' %>

app/views/pages/new.html.erb
<%- model_class = Page -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/pages/show.html.erb
<%- model_class = Page -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:scrapbook_id) %>:</strong></dt>
  <dd><%= @page.scrapbook_id %></dd>
</dl>
<%=raw @page.html %> 

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              scrapbook_pages_path(@scrapbook), :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_scrapbook_page_path(@scrapbook, @page), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              scrapbook_page_path(@scrapbook, @page),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/scrapbooks/_form.html.erb
<%= form_for @scrapbook, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                scrapbooks_path, :class => 'btn' %>
  </div>
<% end %>

app/views/scrapbooks/edit.html.erb
<%- model_class = Scrapbook -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/scrapbooks/index.html.erb
<%- model_class = Scrapbook -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @scrapbooks.each do |scrapbook| %>
      <tr>
        <td><%= link_to scrapbook.id, scrapbook_path(scrapbook) %></td>
        <td><%= scrapbook.name %></td>
        <td><%=l scrapbook.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_scrapbook_path(scrapbook), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      scrapbook_path(scrapbook),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_scrapbook_path,
            :class => 'btn btn-primary' %>

app/views/scrapbooks/new.html.erb
<%- model_class = Scrapbook -%>

<%= render :partial => 'form' %>

app/views/scrapbooks/show.html.erb
<%- model_class = Scrapbook -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @scrapbook.name %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              scrapbooks_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_scrapbook_path(@scrapbook), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              scrapbook_path(@scrapbook),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>